# ===============================
# institutions.yaml  (sikker/ASCII)
# ===============================

aliases:
  "OsloMet - storbyuniversitetet": "oslomet"
  "Universitetet i Agder": "uia"
  "Hogskolen i Innlandet": "inn"
  "Hogskolen i Ostfold": "hiof"
  "Hogskulen pa Vestlandet": "hvl"
  "MF vitenskapelig hoyskole": "mf"
  "NLA Hogskolen": "nla"
  "Nord universitet": "nord"
  "Norges idrettshogskole": "nih"
  "Universitetet i Bergen": "uib"
  "Universitetet i Oslo": "uio"
  "Universitetet i Stavanger": "uis"
  "Universitetet i Sorost-Norge": "usn"
  "UiT Norges arktiske universitet": "uit"
  "Hogskulen i Volda": "hivolda"
  "Norges teknisk-naturvitenskapelige universitet": "ntnu"
  "NTNU": "ntnu"
  "Norges miljo- og biovitenskapelige universitet": "nmbu"
  "NMBU": "nmbu"
  "Samisk hogskole": "samas"
  "Sami allaskuvla": "samas"
  "Steinerhoyskolen": "steiner"

institutions:
  oslomet:
    url_pattern: "https://student.oslomet.no/studier/-/studieinfo/emne/{code_upper_nodashnum}/{year}/{semester_url}"
    semester_style: "oslomet"

  uia:
    url_pattern: "https://www.uia.no/studier/emner/{year}/{semester_url}/{code_lower_nodashnum}.html"
    semester_style: "uia"

  ntnu:
    url_pattern: "https://www.ntnu.no/studier/emner/{code_upper_nosfx1A}#tab=omEmnet"
    semester_style: "plain"

  inn:
    url_pattern: "https://studiekatalog.edutorium.no/inn/nb/emne/{course_code}/{year}-{semester_url}"
    semester_style: "uia"

  hivolda:
    url_pattern: "https://www.hivolda.no/emne/{code_upper_nodashnum}"
    semester_style: "plain"

  hiof:
    url_pattern: "https://www.hiof.no/studier/emner/lusp/lusp/{year}/{semester_url}/{code_lower_nodashnum}.html"
    semester_style: "hiof"

  hvl:
    url_pattern: "https://www.hvl.no/studier/studieprogram/emne/{code_upper_nodashnum}"
    semester_style: "plain"

  mf:
    url_pattern: "https://mf.no/studier/emner/{code_lower_nodashnum}"
    semester_style: "plain"

  nla:
    url_pattern: "https://www.nla.no/studietilbud/emner/{year}/{code_lower_nodashnum}/"
    semester_style: "plain"

  nord:
    url_pattern: "https://www.nord.no/studier/emner/{code_lower_nodashnum}"
    semester_style: "plain"

  nih:
    url_pattern: "https://www.nih.no/studier/emner/{year}/{semester_url}/{code_lower_nodashnum}.html"
    semester_style: "nih"

  uib:
    url_pattern: "https://www4.uib.no/studier/emner/{code_lower_nodashnum}"
    semester_style: "plain"

  uio:
    url_pattern: "https://www.uio.no/studier/emner/{uio_faculty_slug}/{uio_inst_slug}/{code_upper_nodash1}/"
    semester_style: "plain"

  uis:
    url_pattern: "https://www.uis.no/nb/course/{code_upper_nodashnum}"
    semester_style: "plain"

  usn:
    url_pattern: "https://www.usn.no/studier/studie-og-emneplaner/#/emne/{course_code}_{year}_{semester_url}"
    semester_style: "oslomet"

  uit:
    url_pattern: "https://uit.no/utdanning/aktivt/emne/{code_upper_nodash1}"
    semester_style: "plain"

  nmbu:
    url_pattern: "https://www.nmbu.no/emne/{code_upper_nodash1}"
    semester_style: "plain"

  samas:
    url_pattern: ""
    semester_style: "plain"

  steiner:
    url_pattern: ""
    semester_style: "plain"
